---

- name: Install prerequisite packages
  become: yes
  yum:
    name: '{{ item }}'
  with_items:
    - ruby
    - ruby-devel
    - lua
    - lua-devel
    - luajit
    - luajit-devel
    - ctags
    - git
    - python
    - python-devel
    - tcl-devel
    - perl
    - perl-devel
    - perl-ExtUtils-ParseXS
    - perl-ExtUtils-XSpp
    - perl-ExtUtils-CBuilder
    - perl-ExtUtils-Embed
    - ncurses-devel

- name: Create tmp directory
  tempfile:
    state: directory
    suffix: vim-source
  register: tmp

- name: Clone source
  git:
    repo: https://github.com/vim/vim.git
    dest: '{{ tmp.path }}'

- name: Configure
  command: >
    ./configure
    --with-features=huge
    --enable-multibyte
    --enable-rubyinterp=yes
    --enable-pythoninterp=yes
    --with-python-config-dir=/usr/lib/python2.7/config
    --enable-python3interp=yes
    --with-python3-config-dir=/usr/lib/python3.6/config
    --enable-perlinterp=yes
    --enable-luainterp=yes
    --enable-cscope
    --prefix=/usr/local
  args:
    chdir: '{{ tmp.path }}'

- name: Make
  make:
    chdir: '{{ tmp.path }}'
    params:
      VIMRUNTIMEDIR: /usr/local/share/vim/vim80

- name: Install
  become: yes
  make:
    chdir: '{{ tmp.path }}'
    target: install
