- name: Install prerequisite packages
  become: yes
  yum:
    name: '{{ item }}'
  with_items:
    - ruby
    - ruby-devel
    - lua
    - lua-devel
    - luajit
    - luajit-devel
    - ctags
    - git
    - python
    - python-devel
    - tcl-devel
    - perl
    - perl-devel
    - perl-ExtUtils-ParseXS
    - perl-ExtUtils-XSpp
    - perl-ExtUtils-CBuilder
    - perl-ExtUtils-Embed
    - ncurses-devel

- name: Create tmp directory
  tempfile:
    state: directory
    suffix: vim-source
  register: tmp

- name: Clone source
  git:
    repo: https://github.com/vim/vim.git
    dest: '{{ tmp.path }}'

- name: Configure
  command: >
    ./configure
    --with-features=huge
    --enable-multibyte
    --enable-cscope
    --enable-rubyinterp
    --enable-perlinterp
    --enable-luainterp
    --enable-python3interp vi_cv_path_python3=/usr/bin/python3.6
    --with-python3-config-dir=/usr/lib64/python3.6/config-3.6m-x86_64-linux-gnu
    --prefix=/usr/local
    --enable-fail-if-missing
  args:
    chdir: '{{ tmp.path }}'

- name: Make
  make:
    chdir: '{{ tmp.path }}'
    params:
      VIMRUNTIMEDIR: /usr/local/share/vim/vim80

- name: Install
  become: yes
  make:
    chdir: '{{ tmp.path }}'
    target: install
