- name: Clear existing go installation directory
  become: yes
  file:
    path: /usr/local/go
    state: absent

- name: Download and extract go package
  become: yes
  unarchive:
    src: https://redirector.gvt1.com/edgedl/go/go{{ version }}.linux-amd64.tar.gz
    dest: /usr/local/
    remote_src: yes
